USE prac;

DROP TABLE IF EXISTS PAY;
DROP TABLE IF EXISTS COURSE;


CREATE TABLE COURSE (
	
    COURSE_NO INT NOT NULL AUTO_INCREMENT,
    CO_TITLE VARCHAR(30) NOT NULL,		-- 강의명
    C0_INTRO MEDIUMTEXT NOT NULL,		-- 강의 소개
    CO_CTNT MEDIUMTEXT NOT NULL,		-- 강의 내용
    CO_PRICE VARCHAR(8) NOT NULL,		-- 강의 가격
    CO_TEACHER VARCHAR(15) NOT NULL,	-- 강의 선생님
    UPLOAD_DATE datetime NOT NULL,		-- 등록일
    
	THUMB_PATH VARCHAR(300),
    THUMB_ORIGIN VARCHAR(300),
    FILESYSTEM VARCHAR(42),
	HAS_THUMBNAIL INT NOT NULL,			-- 썸네일
    
	CONSTRAINT PRIMARY KEY (COURSE_NO)
); 


CREATE TABLE PAY (

	PAY_NO INT NOT NULL AUTO_INCREMENT,
    COURSE_NO INT NOT NULL,
    PAY_DATE DATETIME NOT NULL,
    
    CONSTRAINT PRIMARY KEY (PAY_NO),
    CONSTRAINT FOREIGN KEY (COURSE_NO) REFERENCES COURSE(COURSE_NO) ON DELETE CASCADE
);
